project_id = "uovuggxuurcdnprewtyl"

[functions.management-ai]
verify_jwt = false

[functions.push-notifier]
verify_jwt = false

[functions.tablet-order]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false